logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb.core: DEBUG
  file:
    path:
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:/security/app.key
  public.key: classpath:/security/app.pub



spring:
  profiles:
    active: security
  data:
    mongodb:
      host: 127.0.0.1
      port: 8080
      database: ZionWebsite
      username: root
      password: 'root'
  main:
    allow-circular-references: true
server:
  port: 9302

zw:
  WeChat:
    PushPlus:
      token: 'YourTokenHere'
      secretKey: 'YourSecretKeyHere'
