logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb.core: DEBUG
  file:
    path:
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:/security/app.key
  public.key: classpath:/security/app.pub



spring:
  profiles:
    active: security
  data:
    mongodb:
      host: 127.0.0.1
      port: 8080
      database: ZionWebsite
      username: root
      password: 'root'
  main:
    allow-circular-references: true

  mail:
    host: smtp.example.com        # 邮箱SMTP服务器地址（如：smtp.163.com）
    port: 587                     # SMTP端口（通常为465或587）
    username: your-email@example.com  # 发送方邮箱账号
    password: your-email-password     # 授权码（不是登录密码！）
    protocol: smtp                # 协议
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 9302

zw:
  WeChat:
    PushPlus:
      token: 'YourTokenHere'
      secretKey: 'YourSecretKeyHere'
